apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: generator
  name: generator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
      - image: docker.io/mezni/generator:latest
        name: generator
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: generator
  name: generator
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: generator
  type: LoadBalancer