version: '3'

services:
  airflow-db:
    image: postgres:13
    hostname: airflow-db
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    #    volumes:
    #      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  redis:
    image: redis:latest
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  airflow-webserver:
    image: apache/airflow:2.7.3
    command: webserver
    hostname: airflow-webserver
    container_name: airflow-webserver
    depends_on:
      - airflow-init
    environment:
      AIRFLOW_DATABASE_URL: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
    ports:
      - "8080:8080"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8080/health"
        ]
      interval: 10s
      retries: 5
      start_period: 5s

  airflow-init:
    image: apache/airflow:2.7.3
    entrypoint: /bin/bash
    depends_on:
      - airflow-db
    command:
      - -c
      - airflow users list || ( airflow db init && airflow users create --role Admin --username airflow --password airflow --email airflow@airflow.com --firstname airflow --lastname airflow )
    restart: on-failure
